# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LNYG0Ejr65MvoOaQ5BbUVP7O7OtFG1uW
"""

import requests
from bs4 import BeautifulSoup
import sqlite3


def scrape_books(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    books = []
    for book in soup.find_all('h2'):
        # print(book)
        books.append(book.text)
    return books


def create_database(books):
    conn = sqlite3.connect('books.db')
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS books
                 (id INTEGER PRIMARY KEY, title TEXT)''')
    for index, book in enumerate(books):
        conn.execute(f"INSERT INTO books VALUES ('{index}', '{book}');")
    conn.commit()
    conn.close()


def get_books_from_database():
    conn = sqlite3.connect('books.db')
    c = conn.cursor()
    c.execute('''SELECT * FROM books''')
    books = c.fetchall()
    conn.close()
    return books


def main():
    books_url = "https://www.slashgear.com/1436422/best-websites-find-download-ebooks-free/"
    books = scrape_books(books_url)
    create_database(books)
    print("Books scraped and stored in database successfully!")

    books = get_books_from_database()
    print("Retrieved books from the database:")
    for book in books:
        print("Title:", book)
        print()

main()

import requests
from bs4 import BeautifulSoup

def scrape_books(url):
    response = requests.get(url)
    if not response.ok:
        raise Exception("Error accessing the URL")
    soup = BeautifulSoup(response.text, 'html.parser')
    books = []
    for book in soup.find_all('h2'):
        books.append(book.text.strip())
    return books

scrape_books("https://www.slashgear.com/1436422/best-websites-find-download-ebooks-free/")